// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentSummoner() {
  return window['go']['main']['App']['CurrentSummoner']();
}

export function InitConnector() {
  return window['go']['main']['App']['InitConnector']();
}
